name: publish

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pack and Publish
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build -c Release src/Cloudtoid.CodeAnalysis.sln

    - name: Pack
      run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Cloudtoid.CodeAnalysis.csproj

    - name: Push
      run: dotnet nuget push Cloudtoid.CodeAnalysis.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_org_api_key }}
